### PR TITLE
Bus set change from read reg to write reg

### PR DESCRIPTION
**Pull request by tomerValerann**

### CODE REVIEW

**Comment by ST-dot-com** [comment]
This pull request has been refused, the <a href='https://cla.st.com'>Contribution License Agreement</a> must be signed.

**Comment by ST-dot-com** [comment]
This pull request has been refused, the <a href='https://cla.st.com'>Contribution License Agreement</a> must be signed.

**Comment by ST-dot-com** [comment]
This pull request has been refused, the <a href='https://cla.st.com'>Contribution License Agreement</a> must be signed.

**Comment by albezanc** [comment]
Hi tomerValerann, the pull request flow needs "Contribution License Agreement".
If you want to start the pull request flow and became an official contributor please accept the [Contribution License Agreement](https://cla.st.com/), otherwise your fix will be added as commit with reference to this item. 

In any case your contribution is really appreciated!

**Pull request closed without merging**
